//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication3.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente_SQL", Namespace="http://schemas.datacontract.org/2004/07/WCFCliente.Dominio")]
    [System.SerializableAttribute()]
    public partial class Cliente_SQL : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ACCIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ANIOMESField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string APORTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string APORTESINIGVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ASIGNADOAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BANCOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CALENDARIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CARGOACUENTAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CATEGORIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CELULARField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CODIGOASESORField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CODIGOPLANField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CONTRATOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EFECTIVIDADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMAILField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMPRESAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ESTADOCARGOACUENTAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ESTADOCUOTAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ESTADOSECUENCIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FECHAEMISIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FECHAVENCIMIENTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FECHAVENCIMIENTOTARJETAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FORMADEPAGOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string INICIOVIGENCIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MOTIVOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBREASESORField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBREDELPLANField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NROCUOTAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NRODOCUMENTOIDENTIDADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NRORENOVACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OBSERVACIONESField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PERSONALIZADO_1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PERSONALIZADO_2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PERSONALIZADO_3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PERSONALIZADO_4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PERSONALIZADO_5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SECUENCIACONTRATOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TELEFONO1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TELEFONO2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TIENEPREEXISTENCIASField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TIPOCARGOACUENTAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TIPODESCUENTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TIPODOCUMENTOIDENTIDADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TITULARField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TRAMOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ULTIMAMODIFICACIONSECUENCIAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ACCION {
            get {
                return this.ACCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.ACCIONField, value) != true)) {
                    this.ACCIONField = value;
                    this.RaisePropertyChanged("ACCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ANIOMES {
            get {
                return this.ANIOMESField;
            }
            set {
                if ((object.ReferenceEquals(this.ANIOMESField, value) != true)) {
                    this.ANIOMESField = value;
                    this.RaisePropertyChanged("ANIOMES");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string APORTE {
            get {
                return this.APORTEField;
            }
            set {
                if ((object.ReferenceEquals(this.APORTEField, value) != true)) {
                    this.APORTEField = value;
                    this.RaisePropertyChanged("APORTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string APORTESINIGV {
            get {
                return this.APORTESINIGVField;
            }
            set {
                if ((object.ReferenceEquals(this.APORTESINIGVField, value) != true)) {
                    this.APORTESINIGVField = value;
                    this.RaisePropertyChanged("APORTESINIGV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ASIGNADOA {
            get {
                return this.ASIGNADOAField;
            }
            set {
                if ((object.ReferenceEquals(this.ASIGNADOAField, value) != true)) {
                    this.ASIGNADOAField = value;
                    this.RaisePropertyChanged("ASIGNADOA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BANCO {
            get {
                return this.BANCOField;
            }
            set {
                if ((object.ReferenceEquals(this.BANCOField, value) != true)) {
                    this.BANCOField = value;
                    this.RaisePropertyChanged("BANCO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CALENDARIO {
            get {
                return this.CALENDARIOField;
            }
            set {
                if ((object.ReferenceEquals(this.CALENDARIOField, value) != true)) {
                    this.CALENDARIOField = value;
                    this.RaisePropertyChanged("CALENDARIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CARGOACUENTA {
            get {
                return this.CARGOACUENTAField;
            }
            set {
                if ((object.ReferenceEquals(this.CARGOACUENTAField, value) != true)) {
                    this.CARGOACUENTAField = value;
                    this.RaisePropertyChanged("CARGOACUENTA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CATEGORIA {
            get {
                return this.CATEGORIAField;
            }
            set {
                if ((object.ReferenceEquals(this.CATEGORIAField, value) != true)) {
                    this.CATEGORIAField = value;
                    this.RaisePropertyChanged("CATEGORIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CELULAR {
            get {
                return this.CELULARField;
            }
            set {
                if ((object.ReferenceEquals(this.CELULARField, value) != true)) {
                    this.CELULARField = value;
                    this.RaisePropertyChanged("CELULAR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODIGOASESOR {
            get {
                return this.CODIGOASESORField;
            }
            set {
                if ((object.ReferenceEquals(this.CODIGOASESORField, value) != true)) {
                    this.CODIGOASESORField = value;
                    this.RaisePropertyChanged("CODIGOASESOR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODIGOPLAN {
            get {
                return this.CODIGOPLANField;
            }
            set {
                if ((object.ReferenceEquals(this.CODIGOPLANField, value) != true)) {
                    this.CODIGOPLANField = value;
                    this.RaisePropertyChanged("CODIGOPLAN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CONTRATO {
            get {
                return this.CONTRATOField;
            }
            set {
                if ((object.ReferenceEquals(this.CONTRATOField, value) != true)) {
                    this.CONTRATOField = value;
                    this.RaisePropertyChanged("CONTRATO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EFECTIVIDAD {
            get {
                return this.EFECTIVIDADField;
            }
            set {
                if ((object.ReferenceEquals(this.EFECTIVIDADField, value) != true)) {
                    this.EFECTIVIDADField = value;
                    this.RaisePropertyChanged("EFECTIVIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMAIL {
            get {
                return this.EMAILField;
            }
            set {
                if ((object.ReferenceEquals(this.EMAILField, value) != true)) {
                    this.EMAILField = value;
                    this.RaisePropertyChanged("EMAIL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMPRESA {
            get {
                return this.EMPRESAField;
            }
            set {
                if ((object.ReferenceEquals(this.EMPRESAField, value) != true)) {
                    this.EMPRESAField = value;
                    this.RaisePropertyChanged("EMPRESA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ESTADOCARGOACUENTA {
            get {
                return this.ESTADOCARGOACUENTAField;
            }
            set {
                if ((object.ReferenceEquals(this.ESTADOCARGOACUENTAField, value) != true)) {
                    this.ESTADOCARGOACUENTAField = value;
                    this.RaisePropertyChanged("ESTADOCARGOACUENTA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ESTADOCUOTA {
            get {
                return this.ESTADOCUOTAField;
            }
            set {
                if ((object.ReferenceEquals(this.ESTADOCUOTAField, value) != true)) {
                    this.ESTADOCUOTAField = value;
                    this.RaisePropertyChanged("ESTADOCUOTA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ESTADOSECUENCIA {
            get {
                return this.ESTADOSECUENCIAField;
            }
            set {
                if ((object.ReferenceEquals(this.ESTADOSECUENCIAField, value) != true)) {
                    this.ESTADOSECUENCIAField = value;
                    this.RaisePropertyChanged("ESTADOSECUENCIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FECHAEMISION {
            get {
                return this.FECHAEMISIONField;
            }
            set {
                if ((object.ReferenceEquals(this.FECHAEMISIONField, value) != true)) {
                    this.FECHAEMISIONField = value;
                    this.RaisePropertyChanged("FECHAEMISION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FECHAVENCIMIENTO {
            get {
                return this.FECHAVENCIMIENTOField;
            }
            set {
                if ((object.ReferenceEquals(this.FECHAVENCIMIENTOField, value) != true)) {
                    this.FECHAVENCIMIENTOField = value;
                    this.RaisePropertyChanged("FECHAVENCIMIENTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FECHAVENCIMIENTOTARJETA {
            get {
                return this.FECHAVENCIMIENTOTARJETAField;
            }
            set {
                if ((object.ReferenceEquals(this.FECHAVENCIMIENTOTARJETAField, value) != true)) {
                    this.FECHAVENCIMIENTOTARJETAField = value;
                    this.RaisePropertyChanged("FECHAVENCIMIENTOTARJETA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FORMADEPAGO {
            get {
                return this.FORMADEPAGOField;
            }
            set {
                if ((object.ReferenceEquals(this.FORMADEPAGOField, value) != true)) {
                    this.FORMADEPAGOField = value;
                    this.RaisePropertyChanged("FORMADEPAGO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string INICIOVIGENCIA {
            get {
                return this.INICIOVIGENCIAField;
            }
            set {
                if ((object.ReferenceEquals(this.INICIOVIGENCIAField, value) != true)) {
                    this.INICIOVIGENCIAField = value;
                    this.RaisePropertyChanged("INICIOVIGENCIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MOTIVO {
            get {
                return this.MOTIVOField;
            }
            set {
                if ((object.ReferenceEquals(this.MOTIVOField, value) != true)) {
                    this.MOTIVOField = value;
                    this.RaisePropertyChanged("MOTIVO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBREASESOR {
            get {
                return this.NOMBREASESORField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBREASESORField, value) != true)) {
                    this.NOMBREASESORField = value;
                    this.RaisePropertyChanged("NOMBREASESOR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBREDELPLAN {
            get {
                return this.NOMBREDELPLANField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBREDELPLANField, value) != true)) {
                    this.NOMBREDELPLANField = value;
                    this.RaisePropertyChanged("NOMBREDELPLAN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NROCUOTA {
            get {
                return this.NROCUOTAField;
            }
            set {
                if ((object.ReferenceEquals(this.NROCUOTAField, value) != true)) {
                    this.NROCUOTAField = value;
                    this.RaisePropertyChanged("NROCUOTA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NRODOCUMENTOIDENTIDAD {
            get {
                return this.NRODOCUMENTOIDENTIDADField;
            }
            set {
                if ((object.ReferenceEquals(this.NRODOCUMENTOIDENTIDADField, value) != true)) {
                    this.NRODOCUMENTOIDENTIDADField = value;
                    this.RaisePropertyChanged("NRODOCUMENTOIDENTIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NRORENOVACION {
            get {
                return this.NRORENOVACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.NRORENOVACIONField, value) != true)) {
                    this.NRORENOVACIONField = value;
                    this.RaisePropertyChanged("NRORENOVACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OBSERVACIONES {
            get {
                return this.OBSERVACIONESField;
            }
            set {
                if ((object.ReferenceEquals(this.OBSERVACIONESField, value) != true)) {
                    this.OBSERVACIONESField = value;
                    this.RaisePropertyChanged("OBSERVACIONES");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PERSONALIZADO_1 {
            get {
                return this.PERSONALIZADO_1Field;
            }
            set {
                if ((object.ReferenceEquals(this.PERSONALIZADO_1Field, value) != true)) {
                    this.PERSONALIZADO_1Field = value;
                    this.RaisePropertyChanged("PERSONALIZADO_1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PERSONALIZADO_2 {
            get {
                return this.PERSONALIZADO_2Field;
            }
            set {
                if ((object.ReferenceEquals(this.PERSONALIZADO_2Field, value) != true)) {
                    this.PERSONALIZADO_2Field = value;
                    this.RaisePropertyChanged("PERSONALIZADO_2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PERSONALIZADO_3 {
            get {
                return this.PERSONALIZADO_3Field;
            }
            set {
                if ((object.ReferenceEquals(this.PERSONALIZADO_3Field, value) != true)) {
                    this.PERSONALIZADO_3Field = value;
                    this.RaisePropertyChanged("PERSONALIZADO_3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PERSONALIZADO_4 {
            get {
                return this.PERSONALIZADO_4Field;
            }
            set {
                if ((object.ReferenceEquals(this.PERSONALIZADO_4Field, value) != true)) {
                    this.PERSONALIZADO_4Field = value;
                    this.RaisePropertyChanged("PERSONALIZADO_4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PERSONALIZADO_5 {
            get {
                return this.PERSONALIZADO_5Field;
            }
            set {
                if ((object.ReferenceEquals(this.PERSONALIZADO_5Field, value) != true)) {
                    this.PERSONALIZADO_5Field = value;
                    this.RaisePropertyChanged("PERSONALIZADO_5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SECUENCIACONTRATO {
            get {
                return this.SECUENCIACONTRATOField;
            }
            set {
                if ((object.ReferenceEquals(this.SECUENCIACONTRATOField, value) != true)) {
                    this.SECUENCIACONTRATOField = value;
                    this.RaisePropertyChanged("SECUENCIACONTRATO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TELEFONO1 {
            get {
                return this.TELEFONO1Field;
            }
            set {
                if ((object.ReferenceEquals(this.TELEFONO1Field, value) != true)) {
                    this.TELEFONO1Field = value;
                    this.RaisePropertyChanged("TELEFONO1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TELEFONO2 {
            get {
                return this.TELEFONO2Field;
            }
            set {
                if ((object.ReferenceEquals(this.TELEFONO2Field, value) != true)) {
                    this.TELEFONO2Field = value;
                    this.RaisePropertyChanged("TELEFONO2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TIENEPREEXISTENCIAS {
            get {
                return this.TIENEPREEXISTENCIASField;
            }
            set {
                if ((object.ReferenceEquals(this.TIENEPREEXISTENCIASField, value) != true)) {
                    this.TIENEPREEXISTENCIASField = value;
                    this.RaisePropertyChanged("TIENEPREEXISTENCIAS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TIPOCARGOACUENTA {
            get {
                return this.TIPOCARGOACUENTAField;
            }
            set {
                if ((object.ReferenceEquals(this.TIPOCARGOACUENTAField, value) != true)) {
                    this.TIPOCARGOACUENTAField = value;
                    this.RaisePropertyChanged("TIPOCARGOACUENTA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TIPODESCUENTO {
            get {
                return this.TIPODESCUENTOField;
            }
            set {
                if ((object.ReferenceEquals(this.TIPODESCUENTOField, value) != true)) {
                    this.TIPODESCUENTOField = value;
                    this.RaisePropertyChanged("TIPODESCUENTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TIPODOCUMENTOIDENTIDAD {
            get {
                return this.TIPODOCUMENTOIDENTIDADField;
            }
            set {
                if ((object.ReferenceEquals(this.TIPODOCUMENTOIDENTIDADField, value) != true)) {
                    this.TIPODOCUMENTOIDENTIDADField = value;
                    this.RaisePropertyChanged("TIPODOCUMENTOIDENTIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TITULAR {
            get {
                return this.TITULARField;
            }
            set {
                if ((object.ReferenceEquals(this.TITULARField, value) != true)) {
                    this.TITULARField = value;
                    this.RaisePropertyChanged("TITULAR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TRAMO {
            get {
                return this.TRAMOField;
            }
            set {
                if ((object.ReferenceEquals(this.TRAMOField, value) != true)) {
                    this.TRAMOField = value;
                    this.RaisePropertyChanged("TRAMO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ULTIMAMODIFICACIONSECUENCIA {
            get {
                return this.ULTIMAMODIFICACIONSECUENCIAField;
            }
            set {
                if ((object.ReferenceEquals(this.ULTIMAMODIFICACIONSECUENCIAField, value) != true)) {
                    this.ULTIMAMODIFICACIONSECUENCIAField = value;
                    this.RaisePropertyChanged("ULTIMAMODIFICACIONSECUENCIA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServiceCliente")]
    public interface IServiceCliente {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCliente/obtenerCliente", ReplyAction="http://tempuri.org/IServiceCliente/obtenerClienteResponse")]
        WpfApplication3.ServiceReference1.Cliente_SQL obtenerCliente(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCliente/obtenerCliente", ReplyAction="http://tempuri.org/IServiceCliente/obtenerClienteResponse")]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.Cliente_SQL> obtenerClienteAsync(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCliente/insertarCliente", ReplyAction="http://tempuri.org/IServiceCliente/insertarClienteResponse")]
        WpfApplication3.ServiceReference1.Cliente_SQL insertarCliente(WpfApplication3.ServiceReference1.Cliente_SQL clienteInsertar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCliente/insertarCliente", ReplyAction="http://tempuri.org/IServiceCliente/insertarClienteResponse")]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.Cliente_SQL> insertarClienteAsync(WpfApplication3.ServiceReference1.Cliente_SQL clienteInsertar);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceClienteChannel : WpfApplication3.ServiceReference1.IServiceCliente, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClienteClient : System.ServiceModel.ClientBase<WpfApplication3.ServiceReference1.IServiceCliente>, WpfApplication3.ServiceReference1.IServiceCliente {
        
        public ServiceClienteClient() {
        }
        
        public ServiceClienteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClienteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClienteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClienteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WpfApplication3.ServiceReference1.Cliente_SQL obtenerCliente(string dni) {
            return base.Channel.obtenerCliente(dni);
        }
        
        public System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.Cliente_SQL> obtenerClienteAsync(string dni) {
            return base.Channel.obtenerClienteAsync(dni);
        }
        
        public WpfApplication3.ServiceReference1.Cliente_SQL insertarCliente(WpfApplication3.ServiceReference1.Cliente_SQL clienteInsertar) {
            return base.Channel.insertarCliente(clienteInsertar);
        }
        
        public System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.Cliente_SQL> insertarClienteAsync(WpfApplication3.ServiceReference1.Cliente_SQL clienteInsertar) {
            return base.Channel.insertarClienteAsync(clienteInsertar);
        }
    }
}
